version: "3.9"
services:
  autocomplete:
    labels:
      - "name=autocomplete"
    image: awais/autocomplete-nestjs
    container_name: autocomplete
    ports:
        - "3000:3000"
    restart: always
    command: bash -cx "npm run start"
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
  mongodb:
      image : mongo:latest
      container_name: mongodb
      ports:
        - 27017:27017
      restart: always
      environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

